"""《病港》— Phase G: HK basemap renderer tests.

Validates the procedural OSM-based basemap generator:
- Output file exists at expected path
- Output is a valid PNG of expected dimensions
- Coords metadata file exists with correct bbox
- All four major HK regions (Kowloon, HK Island, NT, Lantau) are present
  in the rendered area as a smoke test for coverage
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
PY = Path(r"C:\Users\User\AppData\Local\Microsoft\WindowsApps\python3.12.exe")
PNG_PATH = REPO / "public" / "assets" / "hk-basemap.png"
COORDS_PATH = REPO / "public" / "assets" / "hk-basemap-coords.json"
RENDER_SCRIPT = REPO / "scripts" / "render_hk_basemap.py"


def test_render_script_exists():
    assert RENDER_SCRIPT.exists(), f"missing {RENDER_SCRIPT}"


def test_basemap_png_exists():
    """The basemap PNG must be present (pre-generated by render_hk_basemap.py)."""
    if not PNG_PATH.exists():
        pytest.skip(
            f"missing {PNG_PATH} — run: python scripts/render_hk_basemap.py"
        )


def test_basemap_coords_metadata_exists():
    """Coords metadata file must exist alongside the basemap."""
    if not COORDS_PATH.exists():
        pytest.skip(f"missing {COORDS_PATH}")
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    assert "bbox" in coords
    bbox = coords["bbox"]
    # All four required fields
    for key in ("lon_min", "lon_max", "lat_min", "lat_max"):
        assert key in bbox, f"missing bbox.{key}"
    # Sanity: Hong Kong is roughly 113.85-114.45 lon, 22.18-22.55 lat
    assert 113.0 < bbox["lon_min"] < 114.0
    assert 114.0 < bbox["lon_max"] < 115.0
    assert 22.0 < bbox["lat_min"] < 22.5
    assert 22.3 < bbox["lat_max"] < 23.0
    # size_px must match the actual image
    assert "size_px" in coords
    assert coords["size_px"] in (1024, 2048, 4096)


def test_basemap_png_dimensions():
    """PNG should be a square at the declared size."""
    if not PNG_PATH.exists():
        pytest.skip("basemap.png not generated")
    from PIL import Image
    with Image.open(PNG_PATH) as img:
        w, h = img.size
    assert w == h, f"basemap should be square, got {w}x{h}"
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    assert w == coords["size_px"], f"image size {w} != declared {coords['size_px']}"


def test_basemap_png_file_size_reasonable():
    """A 2048x2048 game-style map with thousands of OSM features should
    be at least 30KB and under 2MB (so the file is meaningful but not bloated)."""
    if not PNG_PATH.exists():
        pytest.skip("basemap.png not generated")
    size = PNG_PATH.stat().st_size
    assert 30_000 < size < 2_000_000, f"basemap size {size} out of range"


def test_basemap_contains_color_variation():
    """Smoke test: basemap must not be a solid color (rendering actually
    produced some features)."""
    if not PNG_PATH.exists():
        pytest.skip("basemap.png not generated")
    from PIL import Image
    with Image.open(PNG_PATH) as img:
        colors = img.convert("RGB").getcolors(maxcolors=10_000_000)
    assert colors is not None and len(colors) > 10, (
        f"basemap has only {len(colors) if colors else 0} unique colors"
    )


def test_basemap_known_anchors_within_bbox():
    """All fallback anchor coords (將軍澳 landmarks) must fall inside the basemap bbox."""
    if not COORDS_PATH.exists():
        pytest.skip("coords metadata missing")
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    bbox = coords["bbox"]
    # Test a few key 將軍澳 anchors
    test_pts = [
        (114.27, 22.31, "艾寶琳倖存區"),
        (114.265, 22.315, "大本營"),
        (114.260, 22.318, "將軍澳地鐵站"),
        (114.275, 22.295, "康城"),
    ]
    for lon, lat, name in test_pts:
        assert bbox["lon_min"] <= lon <= bbox["lon_max"], (
            f"{name} lon {lon} outside bbox"
        )
        assert bbox["lat_min"] <= lat <= bbox["lat_max"], (
            f"{name} lat {lat} outside bbox"
        )


def test_lonlat_projection_roundtrip():
    """Test the projection math: bbox corners should map to viewbox corners."""
    from PIL import Image  # noqa: F401  (force load to test env)
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    bbox = coords["bbox"]
    # Image-y axis is inverted relative to latitude (y points down on screen
    # but lat points up geographically). So (lon_min, lat_max) maps to
    # viewbox top-left (113.85, 22.18), and (lon_max, lat_min) to bottom-right
    # (113.85+0.60, 22.18+0.37).
    def project(lon, lat):
        fx = (lon - bbox["lon_min"]) / (bbox["lon_max"] - bbox["lon_min"])
        fy = (bbox["lat_max"] - lat) / (bbox["lat_max"] - bbox["lat_min"])
        return 113.85 + fx * 0.60, 22.18 + fy * 0.37
    # Top-left
    x, y = project(bbox["lon_min"], bbox["lat_max"])
    assert abs(x - 113.85) < 1e-9
    assert abs(y - 22.18) < 1e-9
    # Bottom-right
    x, y = project(bbox["lon_max"], bbox["lat_min"])
    assert abs(x - 114.45) < 1e-9
    assert abs(y - 22.55) < 1e-9
    # Midpoint
    x, y = project(
        (bbox["lon_min"] + bbox["lon_max"]) / 2,
        (bbox["lat_min"] + bbox["lat_max"]) / 2,
    )
    assert abs(x - 114.15) < 1e-9
    assert abs(y - 22.365) < 1e-9


# --------------------------------------------------------------------------
# Phase I: 獨立標籤圖層（label detail overlay）
#
# 次要街道名（secondary / tertiary）唔再燒入底圖，而係輸出成獨立透明
# RGBA PNG，前端 `#label-detail-layer` 按 viewScale 控制透明度。呢組
# 測試鎖定兩個 PNG 嘅關係同透明度特性。
# --------------------------------------------------------------------------
LABELS_PNG_PATH = REPO / "public" / "assets" / "hk-basemap-labels.png"


def test_label_overlay_png_exists():
    if not LABELS_PNG_PATH.exists():
        pytest.skip(
            f"missing {LABELS_PNG_PATH} — run: python scripts/render_hk_basemap.py --skip-fetch"
        )


def test_label_overlay_dimensions_match_basemap():
    """標籤圖層必須同底圖同尺寸，否則疊圖會錯位。"""
    if not LABELS_PNG_PATH.exists() or not PNG_PATH.exists():
        pytest.skip("basemap 或 label overlay 未生成")
    from PIL import Image
    with Image.open(PNG_PATH) as base, Image.open(LABELS_PNG_PATH) as lab:
        assert lab.size == base.size, (
            f"label overlay {lab.size} != basemap {base.size}"
        )


def test_label_overlay_has_alpha_channel():
    """必須係 RGBA（帶 alpha），前端先可以用 opacity 淡入淡出。"""
    if not LABELS_PNG_PATH.exists():
        pytest.skip("label overlay 未生成")
    from PIL import Image
    with Image.open(LABELS_PNG_PATH) as lab:
        assert lab.mode == "RGBA", f"label overlay mode = {lab.mode}，應為 RGBA"


def test_label_overlay_is_mostly_transparent():
    """圖層應該以透明為主（只喺有街道名嘅位置有像素）。"""
    if not LABELS_PNG_PATH.exists():
        pytest.skip("label overlay 未生成")
    from PIL import Image
    with Image.open(LABELS_PNG_PATH) as lab:
        alpha = lab.getchannel("A")
        hist = alpha.histogram()
        transparent = sum(hist[:16])  # alpha < 16
        total = sum(hist)
    ratio = transparent / total
    # 291 個街道標籤（declutter 後）+ 抗鋸齒，實測透明像素約 98.4%。
    # 門檻設 0.95：足以分辨「稀疏疊加圖層」同「整張不透明圖」，
    # 同時一旦標籤重新爆炸（例如 16,887 個 → 透明度跌到 0.81）就會 fail。
    assert ratio > 0.95, f"透明像素比例只有 {ratio:.3f}，標籤可能過密或圖層不透明"


def test_label_overlay_has_visible_pixels():
    """同時必須真係有內容（唔係全透明空圖層）。"""
    if not LABELS_PNG_PATH.exists():
        pytest.skip("label overlay 未生成")
    from PIL import Image
    with Image.open(LABELS_PNG_PATH) as lab:
        alpha = lab.getchannel("A")
        hist = alpha.histogram()
        visible = sum(hist[64:])  # alpha >= 64
    assert visible > 1000, f"可見像素只有 {visible}，圖層可能係空"


def test_coords_metadata_declares_label_layer():
    if not COORDS_PATH.exists():
        pytest.skip("coords metadata missing")
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    layers = coords.get("layers")
    assert layers, "coords 缺少 layers metadata"
    assert layers.get("base") == "hk-basemap.png"
    assert layers.get("label_detail") == "hk-basemap-labels.png"


# ---------------------------------------------------------------------------
# Phase I: 街道標籤 declutter（2026-09-15 修正）
#
# 原本「一段 way 一個標籤」會令同一路名大量重複：實測 16,887 段合資格 way
# 只對應 1,515 個唯一路名（平均 11.1 次），「英皇道 King's Road」重複 130 次。
# 以下測試鎖定 declutter 行為，防止回歸。
# ---------------------------------------------------------------------------


def _load_render_module():
    """用 importlib 載入 render_hk_basemap.py（唔會執行 main）。"""
    import importlib.util

    spec = importlib.util.spec_from_file_location("render_hk_basemap", RENDER_SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _way(name: str, lon: float, lat: float, highway: str = "secondary") -> dict:
    """合成一個最小 Overpass way（兩點，中點約等於畀定座標）。"""
    return {
        "type": "way",
        "tags": {"highway": highway, "name": name},
        "geometry": [
            {"lon": lon - 0.0001, "lat": lat},
            {"lon": lon + 0.0001, "lat": lat},
        ],
    }


@pytest.mark.parametrize(
    "name,expected",
    [
        ("大涌橋路 Tai Chung Kiu Road", "大涌橋路"),
        ("英皇道 King's Road", "英皇道"),
        ("清水灣道 Clear Water Bay Road", "清水灣道"),
        ("Clear Water Bay Road", "Clear Water Bay"),
        ("Queen's Road", "Queen's Road"),
        ("", ""),
    ],
)
def test_short_label_prefers_cjk_and_cuts_at_word_boundary(name, expected):
    """中文名只取中文部分；純英文名退到最後一個完整詞，唔會切斷詞語。"""
    module = _load_render_module()
    assert module._short_label(name) == expected


def test_short_label_caps_cjk_length():
    module = _load_render_module()
    long_cjk = "一二三四五六七八九十"
    out = module._short_label(long_cjk)
    assert out == "一二三四五六七", f"中文應截到 7 字，實得 {out!r}"
    assert len(out) == 7


def test_plan_labels_deduplicates_repeated_road_name():
    """同一路名重複 60 段，最多只應該畫 max_per_name 個標籤。"""
    module = _load_render_module()
    # 沿一條橫線平均分佈 60 段同一路名
    els = [
        _way("測試大道 Test Avenue", 113.90 + i * 0.006, 22.30)
        for i in range(60)
    ]
    placed, stats = module.plan_labels(els, 2048, module._load_label_fonts(2048)[1])
    assert stats["ways"] == 60
    assert stats["names"] == 1
    same = [p for p in placed if p[0] == "測試大道 Test Avenue"]
    assert 0 < len(same) <= 3, f"同名標籤數 {len(same)} 超出上限 3"
    assert len(same) < 60, "應該有去重效果"


def test_plan_labels_respects_min_spacing_for_same_name():
    """同名標籤之間必須隔開（唔可以連續疊埋一齊）。"""
    module = _load_render_module()
    els = [
        _way("測試大道 Test Avenue", 113.90 + i * 0.0004, 22.30)
        for i in range(30)
    ]
    placed, _ = module.plan_labels(els, 2048, module._load_label_fonts(2048)[1])
    same = [p for p in placed if p[0] == "測試大道 Test Avenue"]
    min_px = 0.09 * 2048
    for i in range(len(same)):
        for j in range(i + 1, len(same)):
            dist = ((same[i][1] - same[j][1]) ** 2 + (same[i][2] - same[j][2]) ** 2) ** 0.5
            assert dist >= min_px * 0.99, f"同名標籤距離 {dist:.1f} < {min_px:.1f}"


def test_plan_labels_avoids_collisions_between_different_names():
    """兩個唔同路名放喺同一點 → 只可以畫其中一個（避免疊字）。"""
    module = _load_render_module()
    els = [
        _way("第一街 First Street", 114.10, 22.32),
        _way("第二街 Second Street", 114.10, 22.32),
    ]
    placed, _ = module.plan_labels(els, 2048, module._load_label_fonts(2048)[1])
    assert len(placed) == 1, f"重疊位置應該只畫一個，實得 {len(placed)}"


def test_plan_labels_ignores_irrelevant_ways():
    """非 secondary/tertiary、或者冇名嘅 way 一律唔應該產生標籤。"""
    module = _load_render_module()
    els = [
        _way("住宅小路", 114.10, 22.32, highway="residential"),
        _way("主要高速", 114.11, 22.32, highway="motorway"),
        {
            "type": "way",
            "tags": {"highway": "secondary"},  # 冇 name
            "geometry": [{"lon": 114.12, "lat": 22.32}, {"lon": 114.121, "lat": 22.32}],
        },
        {"type": "node", "tags": {"highway": "secondary", "name": "唔係 way"}},
    ]
    placed, stats = module.plan_labels(els, 2048, module._load_label_fonts(2048)[1])
    assert placed == []
    assert stats["ways"] == 0


def test_plan_labels_is_deterministic():
    """同一輸入必須產生完全相同嘅輸出（可重跑、可驗 hash）。"""
    module = _load_render_module()
    els = [
        _way(f"道路{i % 12}", 113.90 + (i % 30) * 0.008, 22.25 + (i // 30) * 0.01)
        for i in range(90)
    ]
    font = module._load_label_fonts(2048)[1]
    a, _ = module.plan_labels(els, 2048, font)
    b, _ = module.plan_labels(els, 2048, font)
    assert a == b

