"""《病港》— Phase G: HK basemap renderer tests.

Validates the procedural OSM-based basemap generator:
- Output file exists at expected path
- Output is a valid PNG of expected dimensions
- Coords metadata file exists with correct bbox
- All four major HK regions (Kowloon, HK Island, NT, Lantau) are present
  in the rendered area as a smoke test for coverage
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
PY = Path(r"C:\Users\User\AppData\Local\Microsoft\WindowsApps\python3.12.exe")
PNG_PATH = REPO / "public" / "assets" / "hk-basemap.png"
COORDS_PATH = REPO / "public" / "assets" / "hk-basemap-coords.json"
RENDER_SCRIPT = REPO / "scripts" / "render_hk_basemap.py"


def test_render_script_exists():
    assert RENDER_SCRIPT.exists(), f"missing {RENDER_SCRIPT}"


def test_basemap_png_exists():
    """The basemap PNG must be present (pre-generated by render_hk_basemap.py)."""
    if not PNG_PATH.exists():
        pytest.skip(
            f"missing {PNG_PATH} — run: python scripts/render_hk_basemap.py"
        )


def test_basemap_coords_metadata_exists():
    """Coords metadata file must exist alongside the basemap."""
    if not COORDS_PATH.exists():
        pytest.skip(f"missing {COORDS_PATH}")
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    assert "bbox" in coords
    bbox = coords["bbox"]
    # All four required fields
    for key in ("lon_min", "lon_max", "lat_min", "lat_max"):
        assert key in bbox, f"missing bbox.{key}"
    # Sanity: Hong Kong is roughly 113.85-114.45 lon, 22.18-22.55 lat
    assert 113.0 < bbox["lon_min"] < 114.0
    assert 114.0 < bbox["lon_max"] < 115.0
    assert 22.0 < bbox["lat_min"] < 22.5
    assert 22.3 < bbox["lat_max"] < 23.0
    # size_px must match the actual image
    assert "size_px" in coords
    assert coords["size_px"] in (1024, 2048, 4096)


def test_basemap_png_dimensions():
    """PNG should be a square at the declared size."""
    if not PNG_PATH.exists():
        pytest.skip("basemap.png not generated")
    from PIL import Image
    with Image.open(PNG_PATH) as img:
        w, h = img.size
    assert w == h, f"basemap should be square, got {w}x{h}"
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    assert w == coords["size_px"], f"image size {w} != declared {coords['size_px']}"


def test_basemap_png_file_size_reasonable():
    """A 2048x2048 game-style map with thousands of OSM features should
    be at least 30KB and under 2MB (so the file is meaningful but not bloated)."""
    if not PNG_PATH.exists():
        pytest.skip("basemap.png not generated")
    size = PNG_PATH.stat().st_size
    assert 30_000 < size < 2_000_000, f"basemap size {size} out of range"


def test_basemap_contains_color_variation():
    """Smoke test: basemap must not be a solid color (rendering actually
    produced some features)."""
    if not PNG_PATH.exists():
        pytest.skip("basemap.png not generated")
    from PIL import Image
    with Image.open(PNG_PATH) as img:
        colors = img.convert("RGB").getcolors(maxcolors=10_000_000)
    assert colors is not None and len(colors) > 10, (
        f"basemap has only {len(colors) if colors else 0} unique colors"
    )


def test_basemap_known_anchors_within_bbox():
    """All fallback anchor coords (將軍澳 landmarks) must fall inside the basemap bbox."""
    if not COORDS_PATH.exists():
        pytest.skip("coords metadata missing")
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    bbox = coords["bbox"]
    # Test a few key 將軍澳 anchors
    test_pts = [
        (114.27, 22.31, "艾寶琳倖存區"),
        (114.265, 22.315, "大本營"),
        (114.260, 22.318, "將軍澳地鐵站"),
        (114.275, 22.295, "康城"),
    ]
    for lon, lat, name in test_pts:
        assert bbox["lon_min"] <= lon <= bbox["lon_max"], (
            f"{name} lon {lon} outside bbox"
        )
        assert bbox["lat_min"] <= lat <= bbox["lat_max"], (
            f"{name} lat {lat} outside bbox"
        )


def test_lonlat_projection_roundtrip():
    """Test the projection math: bbox corners should map to viewbox corners."""
    from PIL import Image  # noqa: F401  (force load to test env)
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    bbox = coords["bbox"]
    # Image-y axis is inverted relative to latitude (y points down on screen
    # but lat points up geographically). So (lon_min, lat_max) maps to
    # viewbox top-left (113.85, 22.18), and (lon_max, lat_min) to bottom-right
    # (113.85+0.60, 22.18+0.37).
    def project(lon, lat):
        fx = (lon - bbox["lon_min"]) / (bbox["lon_max"] - bbox["lon_min"])
        fy = (bbox["lat_max"] - lat) / (bbox["lat_max"] - bbox["lat_min"])
        return 113.85 + fx * 0.60, 22.18 + fy * 0.37
    # Top-left
    x, y = project(bbox["lon_min"], bbox["lat_max"])
    assert abs(x - 113.85) < 1e-9
    assert abs(y - 22.18) < 1e-9
    # Bottom-right
    x, y = project(bbox["lon_max"], bbox["lat_min"])
    assert abs(x - 114.45) < 1e-9
    assert abs(y - 22.55) < 1e-9
    # Midpoint
    x, y = project(
        (bbox["lon_min"] + bbox["lon_max"]) / 2,
        (bbox["lat_min"] + bbox["lat_max"]) / 2,
    )
    assert abs(x - 114.15) < 1e-9
    assert abs(y - 22.365) < 1e-9


# --------------------------------------------------------------------------
# Phase I: 獨立標籤圖層（label detail overlay）
#
# 次要街道名（secondary / tertiary）唔再燒入底圖，而係輸出成獨立透明
# RGBA PNG，前端 `#label-detail-layer` 按 viewScale 控制透明度。呢組
# 測試鎖定兩個 PNG 嘅關係同透明度特性。
# --------------------------------------------------------------------------
LABELS_PNG_PATH = REPO / "public" / "assets" / "hk-basemap-labels.png"


def test_label_overlay_png_exists():
    if not LABELS_PNG_PATH.exists():
        pytest.skip(
            f"missing {LABELS_PNG_PATH} — run: python scripts/render_hk_basemap.py --skip-fetch"
        )


def test_label_overlay_dimensions_match_basemap():
    """標籤圖層必須同底圖同尺寸，否則疊圖會錯位。"""
    if not LABELS_PNG_PATH.exists() or not PNG_PATH.exists():
        pytest.skip("basemap 或 label overlay 未生成")
    from PIL import Image
    with Image.open(PNG_PATH) as base, Image.open(LABELS_PNG_PATH) as lab:
        assert lab.size == base.size, (
            f"label overlay {lab.size} != basemap {base.size}"
        )


def test_label_overlay_has_alpha_channel():
    """必須係 RGBA（帶 alpha），前端先可以用 opacity 淡入淡出。"""
    if not LABELS_PNG_PATH.exists():
        pytest.skip("label overlay 未生成")
    from PIL import Image
    with Image.open(LABELS_PNG_PATH) as lab:
        assert lab.mode == "RGBA", f"label overlay mode = {lab.mode}，應為 RGBA"


def test_label_overlay_is_mostly_transparent():
    """圖層應該以透明為主（只喺有街道名嘅位置有像素）。"""
    if not LABELS_PNG_PATH.exists():
        pytest.skip("label overlay 未生成")
    from PIL import Image
    with Image.open(LABELS_PNG_PATH) as lab:
        alpha = lab.getchannel("A")
        hist = alpha.histogram()
        transparent = sum(hist[:16])  # alpha < 16
        total = sum(hist)
    ratio = transparent / total
    # 16,887 個街道標籤 + 抗鋸齒，實測透明像素約 81%。門檻設 0.7
    # 足以分辨「稀疏疊加圖層」同「整張不透明圖」。
    assert ratio > 0.7, f"透明像素比例只有 {ratio:.3f}，圖層可能唔透明"


def test_label_overlay_has_visible_pixels():
    """同時必須真係有內容（唔係全透明空圖層）。"""
    if not LABELS_PNG_PATH.exists():
        pytest.skip("label overlay 未生成")
    from PIL import Image
    with Image.open(LABELS_PNG_PATH) as lab:
        alpha = lab.getchannel("A")
        hist = alpha.histogram()
        visible = sum(hist[64:])  # alpha >= 64
    assert visible > 1000, f"可見像素只有 {visible}，圖層可能係空"


def test_coords_metadata_declares_label_layer():
    if not COORDS_PATH.exists():
        pytest.skip("coords metadata missing")
    with COORDS_PATH.open(encoding="utf-8") as f:
        coords = json.load(f)
    layers = coords.get("layers")
    assert layers, "coords 缺少 layers metadata"
    assert layers.get("base") == "hk-basemap.png"
    assert layers.get("label_detail") == "hk-basemap-labels.png"
